# Render deploy configuration for Flask app usando Gunicorn e build customizado
services:
  - type: web
    name: noxsubc
    env: python
    buildCommand: bash render-build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
    staticPublishPath: static
