# Render deploy configuration para Dockerfile customizado
services:
  - type: web
    name: noxsubc
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
    staticPublishPath: static
